# The planned waypoints for carving motion
geometry_msgs/PoseArray path

# [OPTIONAL] The planned motion instructions, if none are defined, the path is assumed to be all linear moves
pumpkin_msgs/MoveInstruction[] instructions
